---
sidebar: sidebar 
permalink: docs/task_mnode_remove_assets.html 
summary: 'Découvrez comment supprimer des nœuds de calcul de votre système à l"aide de l"API REST.' 
keywords: netapp, hci, api, REST, remove, compute, asset 
---
= Supprimer une ressource du nœud de gestion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous remplacez physiquement un nœud de calcul ou que vous devez le supprimer du cluster NetApp HCI, vous devez supprimer cette ressource à l'aide des API de nœud de gestion.

.Ce dont vous avez besoin
* Votre cluster de stockage exécute NetApp Element version 11.3 ou ultérieure.
* Vous avez déployé un nœud de gestion exécutant la version 11.3 ou ultérieure.


.Étapes
. Entrez l'adresse IP du nœud de gestion, puis `/mnode/1/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/1/
----
. Sélectionnez *Authorise* ou toute icône de verrouillage et entrez les informations d'identification d'administrateur de cluster pour les autorisations d'utilisation des API.
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Sélectionnez *corps de demande* dans la liste déroulante type si la valeur n'est pas déjà sélectionnée.
.. Entrez l'ID client comme `mnode-client` si la valeur n'était pas déjà renseignée.
.. N'entrez pas de valeur pour le secret client.
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Fermez la fenêtre.


. Fermez la boîte de dialogue *autorisations disponibles*.
. Sélectionnez *OBTENIR/actifs*.
. Sélectionnez *essayez-le*.
. Sélectionnez *Exécuter*.
. Faites défiler le corps de réponse vers le bas jusqu'à la section *Compute* et copiez les `parent` valeurs et `id` du nœud de calcul défaillant.
. Sélectionnez *DELETE/ASSET/{ASSET_ID}/Compute-nodes/{Compute_ID}*.
. Sélectionnez *essayez-le*.
. Entrez les `parent` valeurs et `id` que vous avez copiées à l'étape précédente.
. Sélectionnez *Exécuter*.

